@url=http://localhost:3000/api/posts

### Get Posts
get {{url}}

### Get ID without category
get {{url}}/5df322aba3968d17e5763354
### Get ID 
get {{url}}/5df321d7a3968d17e5763351
### Post 
post {{url}}
Content-Type: application/json

{
  "text": "test",
  "categoryId": "5df3229fa3968d17e5763353"
}

### Modify 
put {{url}}/5df321d7a3968d17e5763351
Content-Type: application/json

{
  "slug": "test2",
  "text": "这是一条测试 \n ### 标题 ",
  "categoryId": "5df3229fa3968d17e5763353"
}

### Del
delete {{url}}/5df23b155e6133060bffec24
