@url=http://localhost:3000/api/comments

post {{url}}/5df5a8feb82e871b57f6245b
Content-Type: application/json

{
  "author": "tww",
  "mail": "y1",
  "text": "test"
}

### 
get {{url}}?state=0

### get
get {{url}}/5e380c44abbf7c1200327aa5

### reply
post {{url}}/reply/5e380f9f291cd83a0c50d90c
Content-Type: application/json

{
  "author": "tww",
  "content": "### reply",
  "mail": "y1",
  "text": "test"
}

### comments delete
delete {{url}}/5dfb30cb41acb50562525505

### modify comment state
put {{url}}/5dfa0c923f7558699a68b0cf/?state=1