@url=http://localhost:3000/api/posts

### Get Posts
get {{url}}?select=-text
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYwZDc5MjdmZWU2ZjhiNWJlZTUzNTgiLCJ1c2VybmFtZSI6InRlc3QiLCJjb2RlIjoidGlranliY3pkbmc0cDE4eG5wcCIsImlhdCI6MTU3OTkzNDAxOCwiZXhwIjoxNTgwMTkzMjE4fQ.uaFfV48UT5NGnsRvIA_z4uaLF98uPitZJN4WROJ03jU


### Get ID without category
get {{url}}/5df322aba3968d17e5763354
### Get ID 
get {{url}}/5e11b2e00304e43b8a792c5b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYwZDc5MjdmZWU2ZjhiNWJlZTUzNTgiLCJ1c2VybmFtZSI6InRlc3QiLCJjb2RlIjoidGlranliY3pkbmc0cDE4eG5wcCIsImlhdCI6MTU3OTkzNDAxOCwiZXhwIjoxNTgwMTkzMjE4fQ.uaFfV48UT5NGnsRvIA_z4uaLF98uPitZJN4WROJ03jU

### Get Post with slug and category
get {{url}}/study/12334ssssdadsss
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYwZDc5MjdmZWU2ZjhiNWJlZTUzNTgiLCJ1c2VybmFtZSI6InRlc3QiLCJjb2RlIjoidGlranliY3pkbmc0cDE4eG5wcCIsImlhdCI6MTU3OTkzNDAxOCwiZXhwIjoxNTgwMTkzMjE4fQ.uaFfV48UT5NGnsRvIA_z4uaLF98uPitZJN4WROJ03jU

### Get None
get {{url}}/1/1
### Post 
post {{url}}
Content-Type: application/json

{
  "text": "test",
  "categoryId": "5df3229fa3968d17e5763353"
}

### Modify 
put {{url}}/5df321d7a3968d17e5763351
Content-Type: application/json

{
  "slug": "test22",
  "text": "这是一条测试 \n ### 标题 ",
  "categoryId": "5df3229fa3968d17e5763353"
}

### Del
delete {{url}}/5df23b155e6133060bffec24
