@url=http://localhost:3000/api/master

### get
get {{url}}/5df0d7927fee6f8b5bee5358

### sign up
post {{url}}/signup
Content-Type: application/json

{
  "username": "test",
  "password": "1",
  "url": "https://shizuri.net",
  "mail": "yiny@shizuri.net"
}

### modify password
put {{url}}/password/modify
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYwZDc5MjdmZWU2ZjhiNWJlZTUzNTgiLCJVc2VyIjoidGVzdCIsImNvZGUiOiIweTE3cHh6cjI3b3E5OHpsY2FlYnJtIiwiaWF0IjoxNTc2MDY2NTg4LCJleHAiOjE1NzYzMjU3ODh9.ht54S2RoDYdmP3Q3CBRCCZ4LwGvRKKWrBgufSNEtkaU


{
  "id": "5df0d7927fee6f8b5bee5358",
  "oldPassword": "2",
  "password": "1"
}

### login
post {{url}}/login
Content-Type: application/json

{
  "username": "test",
  "password": "1"
}

### login inject 
post {{url}}/login
Content-Type: application/json

{
  "username": {
    "$gt": 1
  },
  "password": "1"
}

### check Logged
get {{url}}/check_logged
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTA3NDk3OWEwZmQ4NjMyNjIwMzRkNzQiLCJVc2VyIjoieWlueSIsImNvZGUiOiIzeHF6dzlreTFxcTJuYm90NGp0NTJpIiwiaWF0IjoxNTc3NjAxNTM2LCJleHAiOjE1Nzc4NjA3MzZ9.lV8oG87ujL0Wd0VFGemx0LpZnN9Xgtb1_CCl5NWQUPY

### sign out
get {{url}}/sign_out
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZGYwZDc5MjdmZWU2ZjhiNWJlZTUzNTgiLCJVc2VyIjoidGVzdCIsImNvZGUiOiIweTE3cHh6cjI3b3E5OHpsY2FlYnJtIiwiaWF0IjoxNTc2MDY2NTg4LCJleHAiOjE1NzYzMjU3ODh9.ht54S2RoDYdmP3Q3CBRCCZ4LwGvRKKWrBgufSNEtkaU

